version: '3.8'

services: 
    # rabbitmq:
    #     image: rabbitmq:3-management
    #     hostname: my-rabbit
    #     ports:
    #         # rabbitmqs will listen on 5672 port and http://localhost:15672 is UI page for 
    #         # rabbitmq setup
    #         - 5672:5672
    #         - 15672:15672

    nodejs:
        build:
            context: ./app
            dockerfile: Dockerfile
        image: app
        ports: 
            - 3000:3000
        volumes:
            - ./app:/appContainer

            # http://localhost:{RHS port} and LHS where express app is listning
    